### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by mk990** [shadwork/Windows-Crunch#1]
crunch.c:256:22: warning: extra tokens at end of #include directive
In file included from crunch.c:256:0:
sys/wait.h:7:6: error: conflicting types for 'sleep'
 void sleep(int seconds);
      ^
In file included from crunch.c:254:0:
c:\mingw\include\unistd.h:139:34: note: previous declaration of 'sleep' was here
 unsigned __cdecl __MINGW_NOTHROW sleep( unsigned );
                                  ^

**Comment by onix-adt** [comment]
Which version of Code::Blocks using ? Works fine with Code::Blocks 13.12 and MinGW, tested on Windows 7 64bit and Windows 8.1 64bit.
Can you provide more information about build environment ?
Also, if you can, please change this lines in crunch.c
#include <sys/wait.h>
#include <sys/types.h>
to 
#include "sys/wait.h"
#include "sys/types.h"
I am trying avoid of any changes inside crunch.c, may be problem placed inside default rules of include search path.
